version: '3.7'
services:
  postgres:
    image: postgres:12.0-alpine
    ports:
      - '9999:9999'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass123